// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Trivial round-trip command used to validate the Rust <-> React IPC + typed
	 *  bindings pipeline (tauri-specta) end to end. Superseded by real commands
	 *  (connections.rs, schema.rs, query.rs, rows.rs, ddl.rs) starting M1.
	 */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  Handles all three dialects. Postgres/MySQL genuinely attempt to connect (the
	 *  pool/auth logic is real); their introspection and query commands still return
	 *  "not yet implemented" until M2 fills in the driver bodies. On success the
	 *  connection is persisted (metadata to the local app store, password to the
	 *  OS keychain) so it survives an app restart.
	 */
	openConnection: (request: NewConnectionRequest) => typedError<OpenedConnection, AppError>(__TAURI_INVOKE("open_connection", { request })),
	closeConnection: (connectionId: string) => typedError<null, AppError>(__TAURI_INVOKE("close_connection", { connectionId })),
	listSavedConnections: () => typedError<SavedConnectionRecord[], AppError>(__TAURI_INVOKE("list_saved_connections")),
	connectSaved: (id: string) => typedError<OpenedConnection, AppError>(__TAURI_INVOKE("connect_saved", { id })),
	deleteSavedConnection: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_saved_connection", { id })),
	listDatabases: (connectionId: string) => typedError<DatabaseInfo[], AppError>(__TAURI_INVOKE("list_databases", { connectionId })),
	/**
	 *  Postgres binds a connection to one database for its lifetime, so switching
	 *  means opening a fresh pool against the target and swapping it in under the
	 *  same connection id — tabs and saved metadata keep working unchanged. The
	 *  saved record is updated so the choice survives a restart.
	 */
	createDatabase: (connectionId: string, database: string) => typedError<null, AppError>(__TAURI_INVOKE("create_database", { connectionId, database })),
	dropDatabase: (connectionId: string, database: string) => typedError<null, AppError>(__TAURI_INVOKE("drop_database", { connectionId, database })),
	switchDatabase: (connectionId: string, database: string) => typedError<null, AppError>(__TAURI_INVOKE("switch_database", { connectionId, database })),
	/**
	 *  Saves edits to an existing connection.
	 * 
	 *  Secrets are only touched when the form actually supplies one: an empty
	 *  password field means "leave the keychain entry alone", so editing the port
	 *  doesn't force the user to retype credentials they can't see.
	 * 
	 *  A live connection is reopened with the new settings, since a pool already
	 *  bound to the old host would otherwise keep serving the previous target. The
	 *  old pool is only torn down once the replacement is known good.
	 */
	updateConnection: (id: string, request: NewConnectionRequest) => typedError<OpenedConnection, AppError>(__TAURI_INVOKE("update_connection", { id, request })),
	/**
	 *  Rebuilds the native menu so File ▸ Open Recent matches the saved connections.
	 *  Called by the frontend after a connection is added or deleted.
	 */
	refreshMenu: () => typedError<null, AppError>(__TAURI_INVOKE("refresh_menu")),
	listSchemas: (connectionId: string) => typedError<SchemaInfo[], AppError>(__TAURI_INVOKE("list_schemas", { connectionId })),
	listTables: (connectionId: string, schema: string | null) => typedError<TableInfo[], AppError>(__TAURI_INVOKE("list_tables", { connectionId, schema })),
	listViews: (connectionId: string, schema: string | null) => typedError<TableInfo[], AppError>(__TAURI_INVOKE("list_views", { connectionId, schema })),
	listFunctions: (connectionId: string, schema: string | null) => typedError<FunctionInfo[], AppError>(__TAURI_INVOKE("list_functions", { connectionId, schema })),
	getColumns: (connectionId: string, schema: string | null, table: string) => typedError<ColumnInfo[], AppError>(__TAURI_INVOKE("get_columns", { connectionId, schema, table })),
	getIndexes: (connectionId: string, schema: string | null, table: string) => typedError<IndexInfo[], AppError>(__TAURI_INVOKE("get_indexes", { connectionId, schema, table })),
	getForeignKeys: (connectionId: string, schema: string | null, table: string) => typedError<ForeignKeyInfo[], AppError>(__TAURI_INVOKE("get_foreign_keys", { connectionId, schema, table })),
	getTriggers: (connectionId: string, schema: string | null, table: string) => typedError<TriggerInfo[], AppError>(__TAURI_INVOKE("get_triggers", { connectionId, schema, table })),
	getTableDdl: (connectionId: string, schema: string | null, table: string) => typedError<string, AppError>(__TAURI_INVOKE("get_table_ddl", { connectionId, schema, table })),
	/**
	 *  Catalog estimate rather than `COUNT(*)`, which is why it can be `None` and
	 *  why it's cheap enough to fetch whenever the details pane opens.
	 * 
	 *  Returned as `f64` so the absent case survives into TypeScript as `null` —
	 *  specta refuses to export a bare `i64`, and annotating it as a number erases
	 *  the `Option`. An f64 is exact well past any row count a table will reach.
	 */
	estimatedRowCount: (connectionId: string, schema: string | null, table: string) => typedError<number | null, AppError>(__TAURI_INVOKE("estimated_row_count", { connectionId, schema, table })),
	fetchRows: (connectionId: string, schema: string | null, table: string, limit: number, offset: number, orderBy: string | null, orderDesc: boolean, filters: ColumnFilter[]) => typedError<RowPage, AppError>(__TAURI_INVOKE("fetch_rows", { connectionId, schema, table, limit, offset, orderBy, orderDesc, filters })),
	insertRow: (connectionId: string, schema: string | null, table: string, values: { [key in string]: DbValue }) => typedError<string, AppError>(__TAURI_INVOKE("insert_row", { connectionId, schema, table, values })),
	updateRow: (connectionId: string, schema: string | null, table: string, pk: { [key in string]: DbValue }, changes: { [key in string]: DbValue }) => typedError<string, AppError>(__TAURI_INVOKE("update_row", { connectionId, schema, table, pk, changes })),
	deleteRows: (connectionId: string, schema: string | null, table: string, pks: { [key in string]: DbValue }[]) => typedError<string[], AppError>(__TAURI_INVOKE("delete_rows", { connectionId, schema, table, pks })),
	runQuery: (connectionId: string, sql: string) => typedError<QueryHandle, AppError>(__TAURI_INVOKE("run_query", { connectionId, sql })),
	fetchMore: (connectionId: string, executionId: string, n: number) => typedError<RowPage, AppError>(__TAURI_INVOKE("fetch_more", { connectionId, executionId, n })),
	cancelQuery: (connectionId: string, executionId: string) => typedError<null, AppError>(__TAURI_INVOKE("cancel_query", { connectionId, executionId })),
	/**
	 *  Splits a SQL script into individual statements, reusing the same logic that
	 *  powers SQL-dump imports so the editor's "Run current" / "Run all" agree with
	 *  what the importer would execute.
	 */
	splitSql: (script: string) => __TAURI_INVOKE<string[]>("split_sql", { script }),
	/**
	 *  Writes a text payload to a file the user picked via the save dialog. Used to
	 *  persist a query as JSON (or any text) without pulling in a filesystem plugin.
	 */
	saveSqlFile: (path: string, contents: string) => typedError<null, AppError>(__TAURI_INVOKE("save_sql_file", { path, contents })),
	/**
	 *  Writes query-result rows to a file as CSV or JSON. The frontend already holds
	 *  the materialised rows from `run_query`/`fetch_more`, so this just serialises
	 *  them — no database round-trip needed.
	 */
	exportQueryResult: (path: string, columns: string[], rows: { [key in string]: DbValue }[], format: string) => typedError<null, AppError>(__TAURI_INVOKE("export_query_result", { path, columns, rows, format })),
	/**
	 *  Returns the SQL that *would* run, without touching the database. The UI shows
	 *  this in a confirmation dialog; `execute_ddl` is a separate call so nothing
	 *  destructive can happen without the user seeing the statements first.
	 */
	previewAlterTable: (connectionId: string, schema: string | null, table: string, diff: TableDiff) => typedError<string[], AppError>(__TAURI_INVOKE("preview_alter_table", { connectionId, schema, table, diff })),
	previewAddColumn: (connectionId: string, schema: string | null, table: string, column: ColumnSpec) => typedError<string[], AppError>(__TAURI_INVOKE("preview_add_column", { connectionId, schema, table, column })),
	previewDropColumn: (connectionId: string, schema: string | null, table: string, column: string) => typedError<string[], AppError>(__TAURI_INVOKE("preview_drop_column", { connectionId, schema, table, column })),
	previewCreateTable: (connectionId: string, spec: TableSpec) => typedError<string[], AppError>(__TAURI_INVOKE("preview_create_table", { connectionId, spec })),
	previewDropTable: (connectionId: string, schema: string | null, table: string) => typedError<string[], AppError>(__TAURI_INVOKE("preview_drop_table", { connectionId, schema, table })),
	previewTruncateTable: (connectionId: string, schema: string | null, table: string) => typedError<string[], AppError>(__TAURI_INVOKE("preview_truncate_table", { connectionId, schema, table })),
	/**
	 *  `new_type` required for MySQL; `default` is `Some(Some("..."))` to set a
	 *  default, `Some(None)` to drop it, and `None` to leave it untouched.
	 */
	previewEditColumn: (connectionId: string, schema: string | null, table: string, column: string, newType: string | null, nullable: boolean | null, newDefault: string | null) => typedError<string[], AppError>(__TAURI_INVOKE("preview_edit_column", { connectionId, schema, table, column, newType, nullable, newDefault })),
	previewCreateIndex: (connectionId: string, schema: string | null, table: string, indexName: string, unique: boolean, columns: string[]) => typedError<string[], AppError>(__TAURI_INVOKE("preview_create_index", { connectionId, schema, table, indexName, unique, columns })),
	previewDropIndex: (connectionId: string, schema: string | null, table: string, indexName: string) => typedError<string[], AppError>(__TAURI_INVOKE("preview_drop_index", { connectionId, schema, table, indexName })),
	executeDdl: (connectionId: string, statements: string[]) => typedError<null, AppError>(__TAURI_INVOKE("execute_ddl", { connectionId, statements })),
	serverInfo: (connectionId: string) => typedError<ServerInfo, AppError>(__TAURI_INVOKE("server_info", { connectionId })),
	listStatementLog: (limit: number) => typedError<StatementLogEntry[], AppError>(__TAURI_INVOKE("list_statement_log", { limit })),
	clearStatementLog: () => typedError<null, AppError>(__TAURI_INVOKE("clear_statement_log")),
	listSavedQueries: () => typedError<SavedQuery[], AppError>(__TAURI_INVOKE("list_saved_queries")),
	saveQuery: (name: string, sql: string) => typedError<SavedQuery, AppError>(__TAURI_INVOKE("save_query", { name, sql })),
	deleteSavedQuery: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_saved_query", { id })),
	exportTables: (connectionId: string, tables: ExportTableSpec[], format: ExportFormat, csvOptions: CsvOptions, destination: string) => typedError<ExportResult, AppError>(__TAURI_INVOKE("export_tables", { connectionId, tables, format, csvOptions, destination })),
	previewCsv: (path: string, options: CsvImportOptions) => typedError<CsvPreview, AppError>(__TAURI_INVOKE("preview_csv", { path, options })),
	importCsv: (connectionId: string, schema: string | null, table: string, path: string, options: CsvImportOptions) => typedError<ImportResult, AppError>(__TAURI_INVOKE("import_csv", { connectionId, schema, table, path, options })),
	importSqlDump: (connectionId: string, path: string) => typedError<ImportResult, AppError>(__TAURI_INVOKE("import_sql_dump", { connectionId, path })),
};

/* Types */
/**  Serializable projection of `DbError` sent across the Tauri IPC boundary. */
export type AppError = {
	kind: string,
	message: string,
};

export type AppInfo = {
	name: string,
	version: string,
};

export type ColumnFilter = {
	column: string,
	operator: FilterOperator,
	/**
	 *  Typed by the frontend from the column's declared type so it binds as the
	 *  right SQL type; ignored for IS NULL / IS NOT NULL.
	 */
	value: DbValue | null,
};

export type ColumnInfo = {
	name: string,
	dataType: string,
	nullable: boolean,
	isPrimaryKey: boolean,
	defaultValue: string | null,
	/**
	 *  Allowed labels when the column's type is an enumeration, in declaration
	 *  order. Empty for every other type, which is how the UI decides whether to
	 *  offer a picker instead of a free-text field.
	 */
	enumValues: string[],
};

export type ColumnSpec = {
	name: string,
	dataType: string,
	nullable: boolean,
	defaultValue: string | null,
};

export type CsvImportOptions = {
	/**
	 *  Treat the first row as column names. When false, values are matched to
	 *  the table's columns positionally.
	 */
	firstRowIsHeader: boolean,
	delimiter: string,
	/**
	 *  Empty fields become NULL rather than an empty string. Usually what you
	 *  want, since an empty string will not cast into a numeric or date column.
	 */
	emptyAsNull: boolean,
};

export type CsvOptions = {
	/**  NULL becomes an empty field rather than the literal text `NULL`. */
	nullToEmpty: boolean,
	lineBreakToSpace: boolean,
	fieldNamesFirstRow: boolean,
	delimiter: string,
	quoting: CsvQuoting,
	lineBreak: string,
	/**  `.` or `,` — the separator used when writing floats and decimals. */
	decimal: string,
};

/**
 *  Reads the header row (or the first data row's width) without consuming the
 *  file, so the UI can show a column mapping before committing to an import.
 */
export type CsvPreview = {
	columns: string[],
	sampleRows: string[][],
};

/**  How to quote CSV fields. Mirrors the "Swap" control in the export dialog. */
export type CsvQuoting = 
/**  Quote only when the value contains a delimiter, quote or line break. */
"IfNeeded" | "Always" | "Never";

export type DatabaseInfo = {
	name: string,
};

/**
 *  Dynamic decode target for a single cell value. Every driver's `decode.rs` must map
 *  into this without panicking — unrecognized/exotic column types fall back to
 *  `Unsupported` rather than crashing the row fetch.
 */
export type DbValue = { type: "Null" } | 
/**
 *  "Use the column's declared default". Write-only — decoding never produces
 *  it — and inlined as the SQL keyword `DEFAULT` rather than bound, the same
 *  way `Null` is. SQLite has no `SET col = DEFAULT`, so its driver rejects it.
 */
{ type: "Default" } | 
/**
 *  "Whatever the server's clock says at write time". Also write-only, and
 *  inlined as `CURRENT_TIMESTAMP` — the spelling every dialect here accepts,
 *  unlike `NOW()`, which SQLite lacks.
 */
{ type: "Now" } | { type: "Bool"; value: boolean } | 
/**
 *  Exported as TS `number`: JSON-wire-compatible with i64, precision loss above
 *  2^53 is an accepted display-only limitation (matches how most DB GUIs handle it).
 */
{ type: "Int"; value: number } | { type: "Float"; value: number | null } | 
/**  Stringified to avoid precision loss through f64. */
{ type: "Decimal"; value: string } | { type: "Text"; value: string } | 
/**  Base64-encoded over IPC. */
{ type: "Bytes"; value: string } | { type: "Json"; value: any } | 
/**  ISO-8601; formatting/timezone display is a frontend concern. */
{ type: "DateTime"; value: string } | { type: "Uuid"; value: string } | { type: "Array"; value: DbValue[] } | { type: "Unsupported"; value: {
	raw: string,
	typeName: string,
} };

export type ExportFormat = "Csv" | "Json" | "Sql";

export type ExportResult = {
	files: string[],
	rowsWritten: number,
};

export type ExportTableSpec = {
	schema: string | null,
	table: string,
	/**  `None` exports every column, in the table's own order. */
	columns: string[] | null,
};

export type FilterOperator = "Equals" | "NotEquals" | "Contains" | "StartsWith" | "EndsWith" | "GreaterThan" | "LessThan" | "GreaterOrEqual" | "LessOrEqual" | "IsNull" | "IsNotNull";

export type ForeignKeyInfo = {
	name: string,
	columns: string[],
	referencedTable: string,
	referencedColumns: string[],
};

export type FunctionInfo = {
	name: string,
	/**  Rendered argument list, e.g. "uid integer, since timestamptz". */
	arguments: string,
	returns: string,
	/**  "function" or "procedure". */
	kind: string,
};

export type ImportResult = {
	rowsImported: number,
	statementsRun: number,
	/**
	 *  Column names in the file that don't exist on the table; their values are
	 *  skipped rather than failing the whole import.
	 */
	skippedColumns: string[],
};

export type IndexInfo = {
	name: string,
	columns: string[],
	isUnique: boolean,
};

export type NewConnectionRequest = {
	dialect: SqlDialect,
	name: string,
	color: string | null,
	host: string | null,
	port: number | null,
	username: string | null,
	password: string | null,
	database: string | null,
	sslMode: string | null,
	sslKeyPath: string | null,
	sslCertPath: string | null,
	sslCaPath: string | null,
	/**  SQLite only. */
	filePath: string | null,
	sshEnabled: boolean,
	sshHost: string | null,
	sshPort: number | null,
	sshUsername: string | null,
	sshPassword: string | null,
	sshUseKey: boolean,
	sshPrivateKeyPath: string | null,
	sshPrivateKeyPassphrase: string | null,
};

export type OpenedConnection = {
	connectionId: string,
	dialect: SqlDialect,
	displayName: string,
	color: string | null,
};

export type QueryExecutionId = string;

export type QueryHandle = {
	executionId: QueryExecutionId,
	firstPage: RowPage,
};

export type RowPage = {
	columns: string[],
	rows: { [key in string]: DbValue }[],
	hasMore: boolean,
	/**
	 *  The statement actually sent to the server, surfaced in the console so the
	 *  UI never has to guess what it ran.
	 */
	sql: string,
};

export type SavedConnectionRecord = {
	id: string,
	name: string,
	dialect: SqlDialect,
	/**
	 *  Hex accent used across the rail and header. Red conventionally marks
	 *  production so destructive actions are visually obvious.
	 */
	color: string | null,
	host: string | null,
	port: number | null,
	username: string | null,
	database: string | null,
	sslMode: string | null,
	sslKeyPath: string | null,
	sslCertPath: string | null,
	sslCaPath: string | null,
	filePath: string | null,
	sshEnabled: boolean,
	sshHost: string | null,
	sshPort: number | null,
	sshUsername: string | null,
	sshUseKey: boolean,
	sshPrivateKeyPath: string | null,
};

export type SavedQuery = {
	id: string,
	name: string,
	sql: string,
	createdAt: string,
};

export type SchemaInfo = {
	name: string,
};

export type ServerInfo = {
	version: string,
	database: string,
};

export type SqlDialect = "Postgres" | "MySql" | "Sqlite";

export type StatementLogEntry = {
	id: string,
	connectionId: string,
	sql: string,
	success: boolean,
	error: string | null,
	durationMs: number,
	executedAt: string,
};

/**
 *  A structural diff between the current and desired shape of a table, used to
 *  build per-dialect ALTER TABLE statement sequences.
 */
export type TableDiff = {
	addedColumns: ColumnSpec[],
	droppedColumns: string[],
	renamedColumns: ([string, string])[],
};

export type TableInfo = {
	name: string,
	isView: boolean,
	estimatedRowCount: number,
};

export type TableSpec = {
	name: string,
	columns: ColumnSpec[],
	primaryKey: string[],
};

export type TriggerInfo = {
	name: string,
	timing: string,
	event: string,
	statement: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

