// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Trivial round-trip command used to validate the Rust <-> React IPC + typed
	 *  bindings pipeline (tauri-specta) end to end. Superseded by real commands
	 *  (connections.rs, schema.rs, query.rs, rows.rs, ddl.rs) starting M1.
	 */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  Handles all three dialects. Postgres/MySQL genuinely attempt to connect (the
	 *  pool/auth logic is real); their introspection and query commands still return
	 *  "not yet implemented" until M2 fills in the driver bodies. On success the
	 *  connection is persisted (metadata to the local app store, password to the
	 *  OS keychain) so it survives an app restart.
	 */
	openConnection: (request: NewConnectionRequest) => typedError<OpenedConnection, AppError>(__TAURI_INVOKE("open_connection", { request })),
	closeConnection: (connectionId: string) => typedError<null, AppError>(__TAURI_INVOKE("close_connection", { connectionId })),
	listSavedConnections: () => typedError<SavedConnectionRecord[], AppError>(__TAURI_INVOKE("list_saved_connections")),
	connectSaved: (id: string) => typedError<OpenedConnection, AppError>(__TAURI_INVOKE("connect_saved", { id })),
	deleteSavedConnection: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_saved_connection", { id })),
	listDatabases: (connectionId: string) => typedError<DatabaseInfo[], AppError>(__TAURI_INVOKE("list_databases", { connectionId })),
	/**
	 *  Postgres binds a connection to one database for its lifetime, so switching
	 *  means opening a fresh pool against the target and swapping it in under the
	 *  same connection id — tabs and saved metadata keep working unchanged. The
	 *  saved record is updated so the choice survives a restart.
	 */
	switchDatabase: (connectionId: string, database: string) => typedError<null, AppError>(__TAURI_INVOKE("switch_database", { connectionId, database })),
	listSchemas: (connectionId: string) => typedError<SchemaInfo[], AppError>(__TAURI_INVOKE("list_schemas", { connectionId })),
	listTables: (connectionId: string, schema: string | null) => typedError<TableInfo[], AppError>(__TAURI_INVOKE("list_tables", { connectionId, schema })),
	listViews: (connectionId: string, schema: string | null) => typedError<TableInfo[], AppError>(__TAURI_INVOKE("list_views", { connectionId, schema })),
	listFunctions: (connectionId: string, schema: string | null) => typedError<FunctionInfo[], AppError>(__TAURI_INVOKE("list_functions", { connectionId, schema })),
	getColumns: (connectionId: string, schema: string | null, table: string) => typedError<ColumnInfo[], AppError>(__TAURI_INVOKE("get_columns", { connectionId, schema, table })),
	getIndexes: (connectionId: string, schema: string | null, table: string) => typedError<IndexInfo[], AppError>(__TAURI_INVOKE("get_indexes", { connectionId, schema, table })),
	getForeignKeys: (connectionId: string, schema: string | null, table: string) => typedError<ForeignKeyInfo[], AppError>(__TAURI_INVOKE("get_foreign_keys", { connectionId, schema, table })),
	getTriggers: (connectionId: string, schema: string | null, table: string) => typedError<TriggerInfo[], AppError>(__TAURI_INVOKE("get_triggers", { connectionId, schema, table })),
	getTableDdl: (connectionId: string, schema: string | null, table: string) => typedError<string, AppError>(__TAURI_INVOKE("get_table_ddl", { connectionId, schema, table })),
	fetchRows: (connectionId: string, schema: string | null, table: string, limit: number, offset: number, orderBy: string | null, orderDesc: boolean, filters: ColumnFilter[]) => typedError<RowPage, AppError>(__TAURI_INVOKE("fetch_rows", { connectionId, schema, table, limit, offset, orderBy, orderDesc, filters })),
	insertRow: (connectionId: string, schema: string | null, table: string, values: { [key in string]: DbValue }) => typedError<string, AppError>(__TAURI_INVOKE("insert_row", { connectionId, schema, table, values })),
	updateRow: (connectionId: string, schema: string | null, table: string, pk: { [key in string]: DbValue }, changes: { [key in string]: DbValue }) => typedError<string, AppError>(__TAURI_INVOKE("update_row", { connectionId, schema, table, pk, changes })),
	deleteRows: (connectionId: string, schema: string | null, table: string, pks: { [key in string]: DbValue }[]) => typedError<string[], AppError>(__TAURI_INVOKE("delete_rows", { connectionId, schema, table, pks })),
	/**
	 *  Returns the SQL that *would* run, without touching the database. The UI shows
	 *  this in a confirmation dialog; `execute_ddl` is a separate call so nothing
	 *  destructive can happen without the user seeing the statements first.
	 */
	previewAlterTable: (connectionId: string, schema: string | null, table: string, diff: TableDiff) => typedError<string[], AppError>(__TAURI_INVOKE("preview_alter_table", { connectionId, schema, table, diff })),
	previewAddColumn: (connectionId: string, schema: string | null, table: string, column: ColumnSpec) => typedError<string[], AppError>(__TAURI_INVOKE("preview_add_column", { connectionId, schema, table, column })),
	previewDropColumn: (connectionId: string, schema: string | null, table: string, column: string) => typedError<string[], AppError>(__TAURI_INVOKE("preview_drop_column", { connectionId, schema, table, column })),
	executeDdl: (connectionId: string, statements: string[]) => typedError<null, AppError>(__TAURI_INVOKE("execute_ddl", { connectionId, statements })),
	serverInfo: (connectionId: string) => typedError<ServerInfo, AppError>(__TAURI_INVOKE("server_info", { connectionId })),
	listStatementLog: (limit: number) => typedError<StatementLogEntry[], AppError>(__TAURI_INVOKE("list_statement_log", { limit })),
	clearStatementLog: () => typedError<null, AppError>(__TAURI_INVOKE("clear_statement_log")),
	listSavedQueries: () => typedError<SavedQuery[], AppError>(__TAURI_INVOKE("list_saved_queries")),
	saveQuery: (name: string, sql: string) => typedError<SavedQuery, AppError>(__TAURI_INVOKE("save_query", { name, sql })),
	deleteSavedQuery: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_saved_query", { id })),
};

/* Types */
/**  Serializable projection of `DbError` sent across the Tauri IPC boundary. */
export type AppError = {
	kind: string,
	message: string,
};

export type AppInfo = {
	name: string,
	version: string,
};

export type ColumnFilter = {
	column: string,
	operator: FilterOperator,
	/**
	 *  Typed by the frontend from the column's declared type so it binds as the
	 *  right SQL type; ignored for IS NULL / IS NOT NULL.
	 */
	value: DbValue | null,
};

export type ColumnInfo = {
	name: string,
	dataType: string,
	nullable: boolean,
	isPrimaryKey: boolean,
	defaultValue: string | null,
};

export type ColumnSpec = {
	name: string,
	dataType: string,
	nullable: boolean,
	defaultValue: string | null,
};

export type DatabaseInfo = {
	name: string,
};

/**
 *  Dynamic decode target for a single cell value. Every driver's `decode.rs` must map
 *  into this without panicking — unrecognized/exotic column types fall back to
 *  `Unsupported` rather than crashing the row fetch.
 */
export type DbValue = { type: "Null" } | { type: "Bool"; value: boolean } | 
/**
 *  Exported as TS `number`: JSON-wire-compatible with i64, precision loss above
 *  2^53 is an accepted display-only limitation (matches how most DB GUIs handle it).
 */
{ type: "Int"; value: number } | { type: "Float"; value: number | null } | 
/**  Stringified to avoid precision loss through f64. */
{ type: "Decimal"; value: string } | { type: "Text"; value: string } | 
/**  Base64-encoded over IPC. */
{ type: "Bytes"; value: string } | { type: "Json"; value: any } | 
/**  ISO-8601; formatting/timezone display is a frontend concern. */
{ type: "DateTime"; value: string } | { type: "Uuid"; value: string } | { type: "Array"; value: DbValue[] } | { type: "Unsupported"; value: {
	raw: string,
	typeName: string,
} };

export type FilterOperator = "Equals" | "NotEquals" | "Contains" | "StartsWith" | "EndsWith" | "GreaterThan" | "LessThan" | "GreaterOrEqual" | "LessOrEqual" | "IsNull" | "IsNotNull";

export type ForeignKeyInfo = {
	name: string,
	columns: string[],
	referencedTable: string,
	referencedColumns: string[],
};

export type FunctionInfo = {
	name: string,
	/**  Rendered argument list, e.g. "uid integer, since timestamptz". */
	arguments: string,
	returns: string,
	/**  "function" or "procedure". */
	kind: string,
};

export type IndexInfo = {
	name: string,
	columns: string[],
	isUnique: boolean,
};

export type NewConnectionRequest = {
	dialect: SqlDialect,
	name: string,
	color: string | null,
	host: string | null,
	port: number | null,
	username: string | null,
	password: string | null,
	database: string | null,
	sslMode: string | null,
	sslKeyPath: string | null,
	sslCertPath: string | null,
	sslCaPath: string | null,
	/**  SQLite only. */
	filePath: string | null,
	sshEnabled: boolean,
	sshHost: string | null,
	sshPort: number | null,
	sshUsername: string | null,
	sshPassword: string | null,
	sshUseKey: boolean,
	sshPrivateKeyPath: string | null,
	sshPrivateKeyPassphrase: string | null,
};

export type OpenedConnection = {
	connectionId: string,
	dialect: SqlDialect,
	displayName: string,
	color: string | null,
};

export type RowPage = {
	columns: string[],
	rows: { [key in string]: DbValue }[],
	hasMore: boolean,
	/**
	 *  The statement actually sent to the server, surfaced in the console so the
	 *  UI never has to guess what it ran.
	 */
	sql: string,
};

export type SavedConnectionRecord = {
	id: string,
	name: string,
	dialect: SqlDialect,
	/**
	 *  Hex accent used across the rail and header. Red conventionally marks
	 *  production so destructive actions are visually obvious.
	 */
	color: string | null,
	host: string | null,
	port: number | null,
	username: string | null,
	database: string | null,
	sslMode: string | null,
	sslKeyPath: string | null,
	sslCertPath: string | null,
	sslCaPath: string | null,
	filePath: string | null,
	sshEnabled: boolean,
	sshHost: string | null,
	sshPort: number | null,
	sshUsername: string | null,
	sshUseKey: boolean,
	sshPrivateKeyPath: string | null,
};

export type SavedQuery = {
	id: string,
	name: string,
	sql: string,
	createdAt: string,
};

export type SchemaInfo = {
	name: string,
};

export type ServerInfo = {
	version: string,
	database: string,
};

export type SqlDialect = "Postgres" | "MySql" | "Sqlite";

export type StatementLogEntry = {
	id: string,
	connectionId: string,
	sql: string,
	success: boolean,
	error: string | null,
	durationMs: number,
	executedAt: string,
};

/**
 *  A structural diff between the current and desired shape of a table, used to
 *  build per-dialect ALTER TABLE statement sequences.
 */
export type TableDiff = {
	addedColumns: ColumnSpec[],
	droppedColumns: string[],
	renamedColumns: ([string, string])[],
};

export type TableInfo = {
	name: string,
	isView: boolean,
	estimatedRowCount: number,
};

export type TriggerInfo = {
	name: string,
	timing: string,
	event: string,
	statement: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

